version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../data:/var/www/html
    restart: always
    ports:
      - ${WEB_SERVER_PORT}:80
    depends_on:
      - phpfpm
  
  phpfpm:
    build: 
      context: ./phpfpm
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-true}
    volumes:
      - ../data:/var/www/html
      - ./phpfpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql
    volumes:
      - db-store:/var/lib/mysql
      - db-log-store:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - ${PHP_ADMIN_PORT}:80
    depends_on:
      - mysql
    
volumes:
  db-store:
  db-log-store: